set( 'MREST_DEBUG_MODE', 1 );
set( 'DBINIT_CONNECT_SUPERAUTH', 'chisel' );
set( 'DOCHAZKA_REST_LOG_FILE', "dochazka-rest.log" );
set( 'DOCHAZKA_REST_LOG_FILE_RESET', 1);
set( 'DOCHAZKA_DBHOST', $ENV{'POSTGRES_PORT_5432_TCP_ADDR'} );
set( 'DOCHAZKA_DBPORT', $ENV{'POSTGRES_PORT_5432_TCP_PORT'} );
